name: Infrastructure Deployment

on:
  workflow_dispatch:

jobs:
  infra-deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install and Test
        run: |
          npm i -g --force yarn  
          yarn install 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 2400
          aws-region: "us-east-1"
          role-skip-session-tagging: true

      - name: CDK Deploy
        run: |
          npm install -g aws-cdk@2.64.0
          cdk deploy --all --require-approval=never --outputs-file ./distributionLink.json

      - name: Extract API Gateway URL and Write to config.json
        run: |
          API_URL=$(jq -r '.["StockPriceAppStack.ApiGatewayUrl"]' distributionLink.json)
          echo "{\"API_ENDPOINT\": \"$API_URL\"}" > config.json

      # Optional: Push config.json to S3
      - name: Upload config.json to S3
        run: |
          aws s3 cp config.json s3://your-s3-bucket-name/path/to/folder/
